const categories = [
  {name:'Alcohol', image: ""},
  {name:'Chewing gum', image: ""},
  {name:'Coffe', image: ""},
  {name:'Credit card', image: ""},
  {name:'Drugs', image: ""},
  {name:'Emotional Shopping', image: ""},
  {name:'Fast Food', image: ""},
  {name:'Flirting', image: ""},
  {name:'Gambling', image: ""},
  {name:'Junk Food', image: ""},
  {name:'Laziness', image: ""},
  {name:'Meat', image: ""},
  {name:'Not Brushing Teeth', image: ""},
  {name:'Other Addictions', image: ""},
  {name:'Overeating', image: ""},
  {name:'Pornography', image: ""},
  {name:'Procrastination', image: ""},
  {name:'Salt', image: ""},
  {name:'Sleeping Late', image: ""},
  {name:'Smoking', image: ""},
  {name:'Social Media', image: ""},
  {name:'Soda', image: ""},
  {name:'Spitting', image: ""},
  {name:'Sugar', image: ""},
  {name:'Swearing', image: ""},
  {name:'Television', image: ""},
  {name:'Telling lie', image: ""},
  {name:'Using Phone in Bed', image: ""},
  {name:'Video Games', image: ""},
]

export default categories;