const categories = [
  { name: "Alcohol", image: "", id: 1 },
  { name: "Chewing gum", image: "", id: 2 },
  { name: "Coffe", image: "", id: 3 },
  { name: "Credit card", image: "", id: 4 },
  { name: "Drugs", image: "", id: 5 },
  { name: "Emotional Shopping", image: "", id: 6 },
  { name: "Fast Food", image: "", id: 7 },
  { name: "Flirting", image: "", id: 8 },
  { name: "Gambling", image: "", id: 9 },
  { name: "Junk Food", image: "", id: 10 },
  { name: "Laziness", image: "", id: 11 },
  { name: "Meat", image: "", id: 12 },
  { name: "Not Brushing Teeth", image: "", id: 13 },
  { name: "Other Addictions", image: "", id: 14 },
  { name: "Overeating", image: "", id: 15 },
  { name: "Pornography", image: "", id: 16 },
  { name: "Procrastination", image: "", id: 17 },
  { name: "Salt", image: "", id: 18 },
  { name: "Sleeping Late", image: "", id: 19 },
  { name: "Smoking", image: "", id: 20 },
  { name: "Social Media", image: "", id: 21 },
  { name: "Soda", image: "", id: 22 },
  { name: "Spitting", image: "", id: 23 },
  { name: "Sugar", image: "", id: 24 },
  { name: "Swearing", image: "", id: 25 },
  { name: "Television", image: "", id: 26 },
  { name: "Telling lie", image: "", id: 27 },
  { name: "Using Phone in Bed", image: "", id: 28 },
  { name: "Video Games", image: "", id: 29 },
];

export default categories;
